name: Python-CI-CD-Workflow

on:
  push:
    branches: [push]

jobs:
  # Первая задача: Тестирование (уже знакомо)
  test-logic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pytest
      - run: pytest test_app.py

  # Вторая задача: Сборка (CD часть)
  build-and-publish:
    needs: test-logic # Эта задача начнется ТОЛЬКО если тесты прошли успешно!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Создаем архив с нашим приложением
      - name: Create Deployment Package
        run: tar -cvf app-package.tar app.py
        
      # Сохраняем этот архив в GitHub, чтобы его можно было скачать
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-ready-app
          path: app-package.tar